name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v3

    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18.0'

    # Run build
    - name: Run build
      run: go build .

    # Vet on the code
    - name: Run vet
      run: go vet .

    - name: Testing Docker Build
      uses: docker/build-push-action@v2
      with:
        tags: on-call-bot:latest
        push: false
